### ISSUE TITLE
CLOUDFLARE_API_TOKEN not found

### ISSUE THREAD

**Issue by totti4ever** [adrianrudnik/fritzbox-cloudflare-dyndns#2]
Hey, why aren't there any issues, yet? Nobody using it am I just to stupid? :-(
I think I set the API token successfully, still the log states that the token is missing. Looking at the code this can only happen, when the token is not set.

Further you are writing in the description that the token should be set in the .env file. From what I understand the .env file only sets variables for the compose file, but does not reach the container: _environment variables defined in the .env file are not automatically visible inside containers._
So I set the var in the _environment:_ area of the compose-file, see below: no change

```
updater_1  | time="2020-11-24T19:45:18Z" level=info msg="Env CLOUDFLARE_API_TOKEN not found, disabling CloudFlare updates"
```

```
$ docker/cloudflare-dns-update$ docker exec -it cloudflare-dns-update_updater_1 sh -c 'echo $CLOUDFLARE_API_TOKEN'
y......................................_
```

What did I do wrong?

**Comment by adrianrudnik** [comment]
Hi totti4ever, it's a small service for a very small user group that uses both.

Seems like the ENV variables are not setup correctly. This program uses godotenv to resolve those variables: First ENV variables, then `.env`, then `.env.dev`. You are not forced to use one or the other.

Did you try the [docker-compose.yml](https://github.com/adrianrudnik/fritzbox-cloudflare-dyndns#docker-compose-setup) example or can you post your own with the credentials removed?

**Comment by adrianrudnik** [comment]
You can also inject env files from the host file structure:

```
services:
  updater:
    ...
    env_file: vars.env
```

or here is an example on how I use it on my NAS currently with network bridging and env pass through from the host ENVs.

```
version: '3.7'

services:
  updater:
    image: adrianrudnik/fritzbox-cloudflare-dyndns:preview
    restart: always
    network_mode: bridge
    environment:
      - DYNDNS_SERVER_BIND=:8080
      - FRITZBOX_ENDPOINT_URL=http://192.168.79.1:49000
      - FRITZBOX_ENDPOINT_TIMEOUT=30s
      - FRITZBOX_ENDPOINT_INTERVAL=31m
      - CLOUDFLARE_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_KEY}
      - CLOUDFLARE_ZONES_IPV4=klonmaschine.de,dev.klonmaschine.de
    ports:
      - "192.168.79.2:41010:8080"
```

and then also use the DynDNS setting on my FRITZ!Box to have a push as well: `http://192.168.79.2:41010/ip?v4=<ipaddr>&v6=<ip6addr>`
