### ISSUE TITLE
Environment Variables defined in compose file not recognized by container

### ISSUE THREAD

**Issue by DHeinrichs** [adrianrudnik/fritzbox-cloudflare-dyndns#9]
Hi,
I was trying to set up your container as part of a compose (v 3.7) with the following config:
```yml
  dyndns:
    container_name: propaganda
    image: adrianrudnik/fritzbox-cloudflare-dyndns
    environment:
      - CLOUDFLARE_API_TOKEN=<API_TOKEN Redacted>
      - CLOUDFLARE_ZONES_IPV6=redacted.domain.com
      - DYNDNS_SERVER_BIND=:8081
      - DYNDNS_SERVER_USERNAME=<user>
      - DYNDNS_SERVER_PASSWORD=<redacted>
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:<redacted>
    networks:
      - srv
```
Running this results in the following error:
```
propaganda | time="2022-12-06T10:19:52Z" level=panic msg="Failed to parse env FRITZBOX_ENDPOINT_URL" error="parse \"http://fritz.box:49000     FRITZBOX_ENDPOINT_TIMEOUT 30s     DYNDNS_SERVER_BIND :8080     DYNDNS_SERVER_USERNAME      DYNDNS_SERVER_PASSWORD      CLOUDFLARE_API_EMAIL      CLOUDFLARE_API_KEY      CLOUDFLARE_ZONES_IPV4      CLOUDFLARE_ZONES_IPV6      CLOUDFLARE_LOCAL_ADDRESS_IPV6 \": invalid port \":8080     DYNDNS_SERVER_USERNAME      DYNDNS_SERVER_PASSWORD      CLOUDFLARE_API_EMAIL      CLOUDFLARE_API_KEY      CLOUDFLARE_ZONES_IPV4      CLOUDFLARE_ZONES_IPV6      CLOUDFLARE_LOCAL_ADDRESS_IPV6 \" after host"
propaganda | panic: (*logrus.Entry) 0xc000317dc0
propaganda |
propaganda | goroutine 1 [running]:
propaganda | github.com/sirupsen/logrus.Entry.log(0xc000172000, 0xc0003f9650, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
propaganda | 	/appbuild/vendor/github.com/sirupsen/logrus/entry.go:239 +0x2ea
propaganda | github.com/sirupsen/logrus.(*Entry).Log(0xc000317d50, 0x0, 0xc00019fe40, 0x1, 0x1)
propaganda | 	/appbuild/vendor/github.com/sirupsen/logrus/entry.go:268 +0xf0
propaganda | github.com/sirupsen/logrus.(*Entry).Panic(0xc000317d50, 0xc00019fe40, 0x1, 0x1)
propaganda | 	/appbuild/vendor/github.com/sirupsen/logrus/entry.go:306 +0x55
propaganda | main.newFritzBox(0x0)
propaganda | 	/appbuild/main.go:61 +0x136
propaganda | main.startPollServer(0xc0000662a0, 0xc0002e2860)
propaganda | 	/appbuild/main.go:158 +0x26
propaganda | main.main()
propaganda | 	/appbuild/main.go:38 +0x125
propaganda exited with code 2
```

It seems like the environment variables are not recognized, is there a known workaround?
